version: '3'
services:
  spring-boot-app:
    image: openjdk:17
    build:
      context: ./TicketsManagementSystem
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:file:/data/ticket_report;DB_CLOSE_ON_EXIT=FALSE
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD:
    volumes:
      - ./data:/data

  h2-database:
    image: oscarfonts/h2
    ports:
      - "8082:8082"
    environment:
      H2_OPTIONS: '-ifNotExists -web -webAllowOthers -tcp -tcpAllowOthers'
